# ---------- LLM ----------
provider: google
model_name: gemini-2.0-flash
google_api_key: "${GOOGLE_API_KEY}"
memory_length: 3 
prompt: |
  You are a patient instructor helping a learner understand this slide.
  Create a brief dialog between two voices that unpacks the slide slowly:
  • First line begins with [S1] and gives a plain-language overview.
  • Second line begins with [S2] and echoes or asks a clarifying question.
  • Continue alternating [S1] / [S2] for 2-6 total lines.
  • Break down key points one at a time, using everyday examples.
  • Make it mid-short and clear.
  • End when the main ideas are clear; do NOT add extra topics.
  • Use no exclamation marks and keep the tone calm.

# ---------- TTS ----------
tts_engine: dia # dia | polly

tts_model: nari-labs/Dia-1.6B
dia_voices:
  s1: 
  s2: 

aws_region: "${AWS_REGION}"
aws_access_key: "${AWS_ACCESS_KEY}"
aws_secret_key: "${AWS_SECRET_KEY}"
polly_voices:
  s1: Ivy
  s2: Brian

# ---------- Rendering ----------
output_suffix: explained
speech_speed: 1

# ---------- cache ----------
models_dir: /app/shared/models
scratch_dir: /tmp/slide_to_vid

# ---------- Runtime ----------
exp_name: 'test' #'new AI6675(1-3)'
test_mode: false # test on the first slide of the first file
files:
  - data/Lecture-1.pdf
  - data/Lecture-2.pdf
  - data/Lecture-3.pdf
